# Generated by Django 5.2 on 2025-04-16 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Unique Stripe payment_intent identifier', max_length=100, null=True, unique=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, help_text='Stripe Checkout session identifier', max_length=100, null=True)),
                ('stripe_charge_id', models.CharField(blank=True, help_text='Stripe charge identifier', max_length=100, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Stripe subscription identifier (if applicable)', max_length=100, null=True)),
                ('payment_type', models.CharField(choices=[('one_time', 'One-Time Payment'), ('subscription', 'Subscription')], default='one_time', help_text='Payment type: one-time payment or subscription', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('currency', models.CharField(default='usd', help_text='Payment currency (e.g., usd)', max_length=10)),
                ('status', models.CharField(choices=[('requires_payment_method', 'Requires Payment Method'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], help_text='Payment status (e.g., succeeded, requires_payment_method)', max_length=50)),
                ('customer_email', models.EmailField(blank=True, help_text='Customer email', max_length=254, null=True)),
                ('customer_name', models.CharField(blank=True, help_text='Customer name', max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method identifier provided by Stripe', max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional payment data in JSON format', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
