# Generated by Django 5.2 on 2025-04-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepayment',
            name='payment_type',
            field=models.CharField(default='one_time', help_text='Payment type: one-time payment or subscription', max_length=20),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='status',
            field=models.CharField(help_text='Payment status (e.g., succeeded, requires_payment_method)', max_length=50),
        ),
    ]
