# Generated by Django 5.2 on 2025-04-26 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_stripepayment_payment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('type', models.CharField(choices=[('one_time', 'One Time'), ('subscription', 'Subscription')], default='one_time', help_text='Product type: one-time or subscription', max_length=20, verbose_name='Type')),
                ('subscription_period', models.DurationField(blank=True, help_text='Duration of subscription (e.g., 30 days). Only applicable for subscriptions.', null=True, verbose_name='Subscription Period')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('stripe_product_id', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Stripe Product ID')),
                ('stripe_price_id', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Stripe Price ID')),
            ],
        ),
    ]
