# Generated by Django 5.2 on 2025-04-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripepayment',
            name='invoice_url',
            field=models.URLField(blank=True, help_text='URL to the Stripe invoice', null=True),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='receipt_url',
            field=models.URLField(blank=True, help_text='URL to the Stripe receipt', max_length=500, null=True),
        ),
    ]
